### ISSUE TITLE
Implement Aesthetic chances from user feedback

### ISSUE THREAD

**Issue by kade-shiro** [simply-savory/simply-savory#48]
Please do work for this task in a branch named issue-48.

- [x] Add hyper links to things in the help & get started sections

- [x] More cards per row on discover & landing

- [x] Change My Recipe to My Recipes

- [x] Need Edit account page

- [x] Change formatting of the Initial Help Page, looks weird to have all text left justified

- [x] Return back to the my recipe page after submitting an edit
- [x] more vivid or darker borders for the items

- [x] Add link to login/signup in landing explanation

- [x] remove periods from landing page bullet points

- [x] grammer errors in landing page

- [x] some pictures looked stretched

- [x] verify password on account creation

- [x] -show a no recipes found message when nothing pops up in search

- [x] css style for hand when hovering clickable link
- [x] verify deleting a recipe

**Comment by tosuzu1** [comment]
More cards per row on discover & landing won't work, smashes images too much, we'll settle for 4
